### ISSUE TITLE
Allow connecting via SSL

### ISSUE THREAD

**Issue by lukechilds** [roccomuso/keyv-etcd#3]
From the `node-etcd` [docs](https://github.com/stianeikeland/node-etcd#ssl-support) it looks like you must provide an `https://*` URL to connect via SSL.

This means if a user connects via `keyv-etcd` with `etcd://hostname` it's impossible for them to use SSL, even if they provide the correct certificate options. (or that's what I gather from the docs)

This might not be obvious and could lead to be people accidentally using insecure connections over the internet in production.

I would suggest adding our own `ssl` option property and then prefix their hostname with the correct scheme.

Something like:

```js
uri = (opts.ssl ? 'https://' : 'http://') + uri;
```

**Comment by roccomuso** [comment]
totally agree. Done!
